name: Build
on:
  push:
    branches:
      - develop

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: 'Tests'
        uses: ./.github/actions/tests

  build:
    name: build
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: 'Validations'
        uses: ./.github/actions/validations

      - name: 'Build and Push'
        uses: ./.github/actions/build-and-push
        with:
          env: 'dev'
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'

      - name: 'Deploy'
        uses: ./.github/actions/deploy
        with:
          env: 'dev'
          image: '${{ env.PUSHED_IMAGE }}'
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AUTH_INTROSPECTION_URL: '${{ secrets.AUTH_INTROSPECTION_URL }}'
          AUTH_CLIENT_ID: '${{ secrets.AUTH_CLIENT_ID }}'
          AUTH_CLIENT_SECRET: '${{ secrets.AUTH_CLIENT_SECRET }}'
