name: Pull Request
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Tests'
        uses: ./.github/actions/tests
