name: Pull Request
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: 'Tests'
        uses: ./.github/actions/tests
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
