name: Build
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Tests'
        uses: ./.github/actions/tests

  build:
    name: build
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: 'Validations'
        uses: ./.github/actions/validations

      - name: 'Build and Push'
        uses: ./.github/actions/build-and-push

      - name: 'Deploy'
        uses: ./.github/actions/deploy
        with:
          env: 'prd'
          image: '${{ env.PUSHED_IMAGE }}'
